name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Verify token received
        run: echo "Token length is ${#TOKEN}"
        env:
          TOKEN: ${{ secrets.METRICS_TOKEN }}

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: xanderflux
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Lagos
